export interface DriverProfile {
	code: string;
	fullName: string;
	firstName: string;
	lastName: string;
	number: number;
	team: string;
	teamColor: string;
	country: string;
	imageUrl: string;
}

export const DRIVERS_DB: Record<string, DriverProfile> = {
	VER: {
		code: "VER",
		fullName: "Max Verstappen",
		firstName: "Max",
		lastName: "Verstappen",
		number: 1,
		team: "Red Bull Racing",
		teamColor: "#3671C6",
		country: "Netherlands",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png",
	},
	PER: {
		code: "PER",
		fullName: "Sergio Pérez",
		firstName: "Sergio",
		lastName: "Pérez",
		number: 11,
		team: "Red Bull Racing",
		teamColor: "#3671C6",
		country: "Mexico",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png",
	},
	HAM: {
		code: "HAM",
		fullName: "Lewis Hamilton",
		firstName: "Lewis",
		lastName: "Hamilton",
		number: 44,
		team: "Ferrari",
		teamColor: "#E8002D",
		country: "United Kingdom",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png",
	},
	RUS: {
		code: "RUS",
		fullName: "George Russell",
		firstName: "George",
		lastName: "Russell",
		number: 63,
		team: "Mercedes",
		teamColor: "#6CD3BF",
		country: "United Kingdom",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png",
	},
	LEC: {
		code: "LEC",
		fullName: "Charles Leclerc",
		firstName: "Charles",
		lastName: "Leclerc",
		number: 16,
		team: "Ferrari",
		teamColor: "#E8002D",
		country: "Monaco",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png",
	},
	SAI: {
		code: "SAI",
		fullName: "Carlos Sainz",
		firstName: "Carlos",
		lastName: "Sainz",
		number: 55,
		team: "Williams Racing",
		teamColor: "#64C4FF",
		country: "Spain",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png",
	},
	NOR: {
		code: "NOR",
		fullName: "Lando Norris",
		firstName: "Lando",
		lastName: "Norris",
		number: 4,
		team: "McLaren",
		teamColor: "#FF8000",
		country: "United Kingdom",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png",
	},
	PIA: {
		code: "PIA",
		fullName: "Oscar Piastri",
		firstName: "Oscar",
		lastName: "Piastri",
		number: 81,
		team: "McLaren",
		teamColor: "#FF8000",
		country: "Australia",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png",
	},
	ALO: {
		code: "ALO",
		fullName: "Fernando Alonso",
		firstName: "Fernando",
		lastName: "Alonso",
		number: 14,
		team: "Aston Martin",
		teamColor: "#229971",
		country: "Spain",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png",
	},
	STR: {
		code: "STR",
		fullName: "Lance Stroll",
		firstName: "Lance",
		lastName: "Stroll",
		number: 18,
		team: "Aston Martin",
		teamColor: "#229971",
		country: "Canada",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png",
	},
	TSU: {
		code: "TSU",
		fullName: "Yuki Tsunoda",
		firstName: "Yuki",
		lastName: "Tsunoda",
		number: 22,
		team: "RB / VCARB",
		teamColor: "#6692FF",
		country: "Japan",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png",
	},
	RIC: {
		code: "RIC",
		fullName: "Daniel Ricciardo",
		firstName: "Daniel",
		lastName: "Ricciardo",
		number: 3,
		team: "RB / VCARB",
		teamColor: "#6692FF",
		country: "Australia",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png",
	},
	GAS: {
		code: "GAS",
		fullName: "Pierre Gasly",
		firstName: "Pierre",
		lastName: "Gasly",
		number: 10,
		team: "Alpine",
		teamColor: "#0093CC",
		country: "France",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png",
	},
	OCO: {
		code: "OCO",
		fullName: "Esteban Ocon",
		firstName: "Esteban",
		lastName: "Ocon",
		number: 31,
		team: "Haas F1 Team",
		teamColor: "#B6BABD",
		country: "France",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png",
	},
	ALB: {
		code: "ALB",
		fullName: "Alexander Albon",
		firstName: "Alexander",
		lastName: "Albon",
		number: 23,
		team: "Williams Racing",
		teamColor: "#64C4FF",
		country: "Thailand",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png",
	},
	MAG: {
		code: "MAG",
		fullName: "Kevin Magnussen",
		firstName: "Kevin",
		lastName: "Magnussen",
		number: 20,
		team: "Haas F1 Team",
		teamColor: "#B6BABD",
		country: "Denmark",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/KEVMAG01_Kevin_Magnussen/kevmag01.png",
	},
	HUL: {
		code: "HUL",
		fullName: "Nico Hülkenberg",
		firstName: "Nico",
		lastName: "Hülkenberg",
		number: 27,
		team: "Sauber / Audi",
		teamColor: "#52E252",
		country: "Germany",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png",
	},
	BOT: {
		code: "BOT",
		fullName: "Valtteri Bottas",
		firstName: "Valtteri",
		lastName: "Bottas",
		number: 77,
		team: "Stake F1 Team",
		teamColor: "#52E252",
		country: "Finland",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png",
	},
	ZHO: {
		code: "ZHO",
		fullName: "Zhou Guanyu",
		firstName: "Guanyu",
		lastName: "Zhou",
		number: 24,
		team: "Stake F1 Team",
		teamColor: "#52E252",
		country: "China",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GUAZHO01_Zhou_Guanyu/guazho01.png",
	},
	BEA: {
		code: "BEA",
		fullName: "Oliver Bearman",
		firstName: "Oliver",
		lastName: "Bearman",
		number: 87,
		team: "Haas F1 Team",
		teamColor: "#B6BABD",
		country: "United Kingdom",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png",
	},
	ANT: {
		code: "ANT",
		fullName: "Kimi Antonelli",
		firstName: "Andrea Kimi",
		lastName: "Antonelli",
		number: 12,
		team: "Mercedes",
		teamColor: "#6CD3BF",
		country: "Italy",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/KIMANT01_Kimi_Antonelli/kimant01.png",
	},
	DOO: {
		code: "DOO",
		fullName: "Jack Doohan",
		firstName: "Jack",
		lastName: "Doohan",
		number: 7,
		team: "Alpine",
		teamColor: "#0093CC",
		country: "Australia",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/J/JACDOO01_Jack_Doohan/jacdoo01.png",
	},
	BOR: {
		code: "BOR",
		fullName: "Gabriel Bortoleto",
		firstName: "Gabriel",
		lastName: "Bortoleto",
		number: 5,
		team: "Sauber / Audi",
		teamColor: "#52E252",
		country: "Brazil",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GABBOR01_Gabriel_Bortoleto/gabbor01.png",
	},
	LAW: {
		code: "LAW",
		fullName: "Liam Lawson",
		firstName: "Liam",
		lastName: "Lawson",
		number: 30,
		team: "Red Bull Racing",
		teamColor: "#3671C6",
		country: "New Zealand",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LIALAW01_Liam_Lawson/lialaw01.png",
	},
	HAD: {
		code: "HAD",
		fullName: "Isack Hadjar",
		firstName: "Isack",
		lastName: "Hadjar",
		number: 6,
		team: "RB / VCARB",
		teamColor: "#6692FF",
		country: "France",
		imageUrl: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/I/ISAHAD01_Isack_Hadjar/isahad01.png",
	},
};

export function getDriverProfile(code: string): DriverProfile {
	const c = (code || "").toUpperCase().trim();
	if (DRIVERS_DB[c]) return DRIVERS_DB[c];

	return {
		code: c || "DRV",
		fullName: c || "F1 Driver",
		firstName: c || "Driver",
		lastName: "",
		number: 0,
		team: "Formula 1",
		teamColor: "#10b981",
		country: "Global",
		imageUrl: `https://ui-avatars.com/api/?name=${c}&background=18181b&color=10b981&bold=true&size=128`,
	};
}
